name: celltosoul
favicon: null
layout_spectrum: 0.02056684740819037
typography_spectrum: 0.7580113138537854
title: Vitality at its best
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d6b4db'
    - '#ff6466'
    - '#312322'
    - '#a57e76'
  brandStrength: 0.1875
  lightness: 0.3554671367164701
  saturation: 0.24020036635920405
  rhythmicContrast: 0.06537409173324704
purpose: []
